class Agent:
    def __init__(self):
        ...

    def eval():
        ...

    def load():
        ...

    def save(self):
        ...

    def policy(self, observation):
        ...        

    def learn(self, obs, action, reward, next_obs, done):
        ...