# Environment
dt: 0.1
max_episode_steps: 2048
behavior_cfg: config

# Model
model:
  path: checkpoints
  mode: train
  actor_type: standard

  space:
    n_actions: 5
    drone_features: 4
    animal_features: 8
    other_drone_features: 0
    action_type: rel   # [rel, abs]

  optimization:
    gamma: 0.99
    actor_lr: 0.0003
    critic_lr: 0.0003
    gae_lambda: 0.95
    policy_clip: 0.2
    val_loss_coef: 0.5
    entropy_start_coef: 0.02
    entropy_end_coef: 0.002

  sampling:
    total_timesteps: 800_000
    rollout_steps: 2048
    mini_batch_size: 256
    n_epochs: 10

# Drone configuration
drone:
  large:
    count: 1
    view_range: 200
    disturbance_mult: 1.0
    min_speed: 0
    max_speed: 25
    ver_angle: 90
    hor_angle: 140
    max_cam_rot: 90
    spawn_dist: [70, 90]
    view_dir: [1, 0, -0.7]
    max_altitude: 150

# Animal configuration
animal:
  env:
    count: 1

  init:
    min_speed: 0
    max_speed: 12
    behavior: EE_CFG
    movement_dim: TWO_D
    max_spawn_radius: 200

# Disturbance model
max_angle_activation: 0.2
max_heading_activation: 0.2
max_axis_activation: 0.2

# Reward
disturbance_penalty_scale: 0.3
p_vel_scale: 0.01
p_theta_scale: 0.01
p_dir_change_scale: 0.02

# Termination / visibility recovery
track_loss_grace: 50
not_visible_penalty: 0.1

# Resource model
resource:
  p_wavelenght: 200
  p_reduction: 0.2
  p_scale: 0.4
  sample_res: 5
  kernel_size: 250
  min_poi_p: 1.0e-2