# Environment
dt: 0.1
max_episode_steps: 2048
behavior_cfg: behaviors_t5/spur_winged_lapwings_km_sm

# Model
model:
  path: checkpoints
  mode: train
  actor_type: standard

  space:
    n_actions: 5
    drone_features: 5
    animal_features: 8
    other_drone_features: 0
    action_type: rel   # [rel, abs]

  optimization:
    gamma: 0.99
    actor_lr: 0.0003
    critic_lr: 0.0003
    gae_lambda: 0.95
    policy_clip: 0.2
    val_loss_coef: 0.5
    entropy_start_coef: 0.02
    entropy_end_coef: 0.001

  sampling:
    total_timesteps: 800_000
    rollout_steps: 8192
    mini_batch_size: 256
    n_epochs: 4

drone:
  large:
    count: 1
    disturbance_mult: 1.0
    hor_angle: 140
    ver_angle: 90
    view_range: 200
    max_cam_rot: 90
    min_speed: 0
    max_speed: 45
    max_altitude: 150
    spawn_dist: [70, 90]
    view_dir: [1, 0, -0.7]

# Animal configuration
animal:
  env:
    count: 1

  init:
    min_speed: 0
    max_speed: 12
    behavior: EE_CFG
    movement_dim: TWO_D
    max_spawn_radius: 400

# Disturbance/reward model
XY_scale: 80
Z_scale: 60
w_angle: 1.0
w_axis: 0.2
w_heading: 1.0

D_R_scale: 0.55 # Disturbance reward tradeoff

p_vel_scale: 0.1
p_theta_scale: 0.1
p_dir_change_scale: 0.1

# Termination / visibility recovery
track_loss_grace: 50
not_visible_penalty: 0.1

# Resource model
resource:
  p_wavelenght: 200
  p_reduction: 0.2
  p_scale: 0.4
  sample_res: 5
  kernel_size: 250
  min_poi_p: 1.0e-2