_config_name:
    value: train
_wandb:
    value:
        cli_version: 0.25.0
        e:
            q2fw93eyk4bxg1fnhx6hnnmqnj1ugqql:
                args:
                    - --config
                    - train
                    - --agent
                    - ppo
                    - --seed
                    - "42"
                    - --wandb
                email: mahmut.osmanovic@outlook.com
                executable: /home/maso/miniconda3/envs/msc/bin/python
                git:
                    commit: 2999b47ff115df2af1c931b617c8bf9a0fdccf3f
                    remote: git@github.com:mosmar99/Stealth-Fleet.git
                host: maso
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: -m scripts.train_agent
                python: CPython 3.12.12
                root: /home/maso/university/Stealth-Fleet
                startedAt: "2026-03-06T20:40:44.718336Z"
                writerId: q2fw93eyk4bxg1fnhx6hnnmqnj1ugqql
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 15
                - 16
            "4": 3.12.12
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
agent_type:
    value: ppo
animal:
    value:
        env:
            count: 1
        init:
            behavior:
                bias_gain: 0
                persistence: 0.9
                speed_sigma: 0.03
                speed_smooth: 0.2
                target_speed: 10
                turn_sigma: 0.15
            max_spawn_radius: 200
            max_speed: 6
            min_speed: 0
            movement_dim: TWO_D
drone:
    value:
        large:
            count: 1
            disturbance_mult: 1
            hor_angle: 140
            max_altitude: 150
            max_cam_rot: 90
            max_speed: 8
            min_speed: 0
            spawn_dist:
                - 40
                - 100
            ver_angle: 90
            view_dir:
                - 1
                - 0
                - -0.7
            view_range: 400
dt:
    value: 0.1
max_angle_boost:
    value: 1
max_episode_steps:
    value: 2048
max_heading_boost:
    value: 1
max_speed_boost:
    value: 1
model:
    value:
        mode: train
        optimization:
            actor_lr: 0.0003
            critic_lr: 0.0003
            entropy_end_coef: 0.01
            entropy_start_coef: 0.5
            gae_lambda: 0.95
            gamma: 0.99
            policy_clip: 0.2
            val_loss_coef: 0.5
        path: checkpoints
        sampling:
            mini_batch_size: 128
            n_epochs: 8
            rollout_steps: 1024
            total_timesteps: 2000000
        space:
            features: 8
            n_actions: 5
resource:
    value:
        kernel_size: 250
        min_poi_p: 0.01
        p_reduction: 0.2
        p_scale: 0.4
        p_wavelenght: 200
        sample_res: 5
run_dir:
    value: /home/maso/university/Stealth-Fleet/runs/train_seed42_2026-03-06_21-40-43
seed:
    value: 42
